import { PhotoSpot } from "@/types/spot";

export const spots: PhotoSpot[] = [
  // ── RAJASTHAN ──────────────────────────────────────────────────────────────
  {
    id: "taj-mahal-agra",
    name: "Taj Mahal – Mehtab Bagh Viewpoint",
    description:
      "The classic reflection shot across the Yamuna River from Mehtab Bagh. Pre-dawn gives you the monument lit by a warm glow with minimal tourists, and the Yamuna can mirror the dome on calm mornings.",
    region: "Rajasthan",
    state: "Uttar Pradesh",
    lat: 27.175, lng: 78.0421,
    cameraLat: 27.1858, cameraLng: 78.0413,
    subjectLat: 27.1751, subjectLng: 78.0421,
    shotTypes: ["architecture", "landscape", "portrait"],
    bestMonths: [10, 11, 12, 1, 2, 3],
    bestTimeOfDay: ["sunrise", "golden_hour_am", "blue_hour"],
    crowdLevel: "high",
    accessibility: "easy",
    monsoonAccessible: false,
    festivalNearby: ["Taj Mahotsav (Feb)"],
    tips: "Arrive 30 min before sunrise. Bring a tripod—long exposures at blue hour are stunning. Avoid June–August (haze + rain).",
    parkingNotes: "Park at Shilpgram; auto-rickshaw to Mehtab Bagh.",
    coverImage: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80",
    tags: ["UNESCO", "iconic", "reflection", "mughal"],
    featured: true,
  },
  {
    id: "jaisalmer-fort-sunset",
    name: "Jaisalmer Fort – Sunset Bastions",
    description:
      "The 'Golden Fort' glows like liquid amber at sunset. Shoot from the sand dunes to the west of the city for the full silhouette, or climb to the fort rooftop for a city-and-dune panorama.",
    region: "Rajasthan",
    state: "Rajasthan",
    lat: 26.9124, lng: 70.9103,
    cameraLat: 26.9100, cameraLng: 70.9050,
    subjectLat: 26.9124, subjectLng: 70.9103,
    shotTypes: ["architecture", "landscape"],
    bestMonths: [10, 11, 12, 1, 2, 3],
    bestTimeOfDay: ["golden_hour_pm", "sunset", "blue_hour"],
    crowdLevel: "medium",
    accessibility: "easy",
    monsoonAccessible: false,
    festivalNearby: ["Desert Festival (Feb)"],
    tips: "Shoot from Vyas Chhatri viewpoint for the best skyline. Yellow sandstone at the golden hour is unmatched.",
    coverImage: "https://images.unsplash.com/photo-1477587458883-47145ed68b07?w=800&q=80",
    tags: ["desert", "golden", "fort", "Thar"],
    featured: true,
  },
  {
    id: "sam-sand-dunes",
    name: "Sam Sand Dunes – Star Trails",
    description:
      "One of India's best dark-sky locations. In winter, the Milky Way core is absent but the starfield and constellation trails are spectacular. The dunes provide compelling foreground silhouettes.",
    region: "Rajasthan",
    state: "Rajasthan",
    lat: 26.8833, lng: 70.5667,
    shotTypes: ["astro", "landscape"],
    bestMonths: [10, 11, 12, 1, 2],
    bestTimeOfDay: ["night", "blue_hour"],
    crowdLevel: "low",
    accessibility: "moderate",
    monsoonAccessible: false,
    festivalNearby: ["Desert Festival (Feb)"],
    tips: "Check moon phase—new moon window is ideal. Rent a camel for a foreground element at blue hour.",
    parkingNotes: "Drive 40 km west of Jaisalmer on NH15.",
    coverImage: "https://images.unsplash.com/photo-1524230572899-a752b3835840?w=800&q=80",
    tags: ["astro", "dunes", "dark-sky", "stars"],
    elevation: 225,
    featured: true,
  },
  {
    id: "ranthambore-tigers",
    name: "Ranthambore – Zone 3 & 4 Tiger Meadows",
    description:
      "India's most photogenic tiger reserve. Zones 3 & 4 hold the famous Jogi Mahal ruins with tigers in the foreground. Crocodiles, leopards, and painted storks are bonus subjects.",
    region: "Rajasthan",
    state: "Rajasthan",
    lat: 26.0173, lng: 76.5026,
    shotTypes: ["wildlife"],
    bestMonths: [3, 4, 5, 10, 11],
    bestTimeOfDay: ["sunrise", "golden_hour_am", "golden_hour_pm"],
    crowdLevel: "high",
    accessibility: "easy",
    monsoonAccessible: false,
    tips: "Book a Canter or Jeep safari 90 days in advance. 400mm+ lens recommended. Morning safaris are best.",
    coverImage: "https://images.unsplash.com/photo-1615729947596-a598e5de0ab3?w=800&q=80",
    tags: ["wildlife", "tigers", "safari", "ranthambore"],
    featured: true,
  },

  // ── LADAKH ────────────────────────────────────────────────────────────────
  {
    id: "pangong-lake-ladakh",
    name: "Pangong Tso – Lukung Shore",
    description:
      "The impossibly blue lake changes colour through the day—turquoise at noon, deep indigo at dusk. Shoot east for sunrise reflections with the Himalayan ridgeline. Location made famous by '3 Idiots'.",
    region: "Ladakh",
    state: "Ladakh",
    lat: 33.7597, lng: 78.6516,
    cameraLat: 33.7580, cameraLng: 78.6500,
    shotTypes: ["landscape", "astro"],
    bestMonths: [6, 7, 8, 9],
    bestTimeOfDay: ["sunrise", "golden_hour_am", "sunset", "night"],
    crowdLevel: "medium",
    accessibility: "difficult",
    monsoonAccessible: true,
    tips: "Altitude is 4,350m—acclimatise in Leh for 2 days first. Bring warm layers even in July.",
    parkingNotes: "Camps at Lukung and Spangmik. Inner Line Permit required.",
    coverImage: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80",
    tags: ["lake", "Himalayas", "altitude", "blue-water"],
    elevation: 4350,
    featured: true,
  },
  {
    id: "nubra-valley-ladakh",
    name: "Nubra Valley – Hunder Dunes & Bactrian Camels",
    description:
      "A surreal cold desert with white sand dunes flanked by snow peaks. Double-humped Bactrian camels are the signature subject. Diskit Monastery at golden hour provides a spiritual backdrop.",
    region: "Ladakh",
    state: "Ladakh",
    lat: 34.5794, lng: 77.6468,
    shotTypes: ["landscape", "wildlife", "portrait"],
    bestMonths: [6, 7, 8, 9],
    bestTimeOfDay: ["golden_hour_am", "golden_hour_pm", "sunset"],
    crowdLevel: "medium",
    accessibility: "difficult",
    monsoonAccessible: true,
    tips: "Shoot camels in the soft morning light—harsh midday shadows ruin the dunes. Permit needed from Leh.",
    coverImage: "https://images.unsplash.com/photo-1609501676725-7186f017a4b7?w=800&q=80",
    tags: ["camels", "dunes", "snow-peaks", "monastery"],
    elevation: 3050,
    featured: false,
  },
  {
    id: "magnetic-hill-road",
    name: "Magnetic Hill – Leh–Kargil Highway Minimalism",
    description:
      "Straight ribbon road cutting through an arid moonscape with the Indus valley below. Wide-angle minimalist compositions work brilliantly. Dawn fog sometimes fills the valley.",
    region: "Ladakh",
    state: "Ladakh",
    lat: 34.1742, lng: 77.2107,
    shotTypes: ["landscape", "aerial"],
    bestMonths: [6, 7, 8, 9],
    bestTimeOfDay: ["sunrise", "golden_hour_am", "golden_hour_pm"],
    crowdLevel: "low",
    accessibility: "easy",
    monsoonAccessible: true,
    tips: "35mm or 24mm lens for sweeping road compositions. Shoot early to avoid traffic.",
    coverImage: "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80",
    tags: ["road", "minimalism", "arid", "Indus"],
    elevation: 3500,
    featured: false,
  },

  // ── HIMACHAL PRADESH ──────────────────────────────────────────────────────
  {
    id: "spiti-key-monastery",
    name: "Key Monastery – Spiti Valley",
    description:
      "A thousand-year-old monastery perched on a pyramid-shaped hill above the Spiti River. Best shot at sunrise when pink light hits the white walls with snow peaks behind. Milky Way shoots possible in summer.",
    region: "Himachal Pradesh",
    state: "Himachal Pradesh",
    lat: 32.2966, lng: 78.0096,
    shotTypes: ["architecture", "landscape", "astro"],
    bestMonths: [5, 6, 7, 8, 9],
    bestTimeOfDay: ["sunrise", "golden_hour_am", "night"],
    crowdLevel: "low",
    accessibility: "difficult",
    monsoonAccessible: false,
    tips: "Shoot from the road bend 500m south for the classic framing. Altitude 4,166m—go slow.",
    coverImage: "https://images.unsplash.com/photo-1591018533289-b0e9dafbf2bc?w=800&q=80",
    tags: ["monastery", "Spiti", "Himalayas", "astro"],
    elevation: 4166,
    featured: true,
  },
  {
    id: "triund-ridge-mcleod",
    name: "Triund Ridge – Dharamsala",
    description:
      "A 9km trek rewards you with a high ridge viewpoint directly opposite the Dhauladhar snow wall. Clouds rolling in at sunset or a post-rain clear sky offer jaw-dropping drama.",
    region: "Himachal Pradesh",
    state: "Himachal Pradesh",
    lat: 32.2958, lng: 76.3469,
    shotTypes: ["landscape", "astro"],
    bestMonths: [3, 4, 5, 9, 10, 11],
    bestTimeOfDay: ["sunset", "golden_hour_pm", "night"],
    crowdLevel: "medium",
    accessibility: "moderate",
    monsoonAccessible: false,
    tips: "Camp overnight for sunrise light on the snow wall. Avoid monsoon—trails are slippery.",
    coverImage: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=800&q=80",
    tags: ["trekking", "snow", "Dhauladhar", "campsite"],
    elevation: 2828,
    featured: false,
  },

  // ── UTTARAKHAND ───────────────────────────────────────────────────────────
  {
    id: "valley-of-flowers",
    name: "Valley of Flowers – Pushpawati River Meadow",
    description:
      "A UNESCO World Heritage alpine meadow that erupts in colour Jul–Aug with 300+ wildflower species. The carpet of Brahmakamal, Cobra Lily, and Blue Poppy against snow peaks is unique on Earth.",
    region: "Uttarakhand",
    state: "Uttarakhand",
    lat: 30.7281, lng: 79.6065,
    shotTypes: ["landscape", "portrait"],
    bestMonths: [7, 8],
    bestTimeOfDay: ["midday", "golden_hour_pm"],
    crowdLevel: "low",
    accessibility: "difficult",
    monsoonAccessible: true,
    tips: "Macro lens is essential. Peak bloom is mid-July. 17km trek from Govindghat.",
    coverImage: "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=800&q=80",
    tags: ["wildflowers", "UNESCO", "alpine", "trekking"],
    elevation: 3600,
    featured: true,
  },
  {
    id: "roopkund-lake",
    name: "Roopkund Lake – Skeleton Lake",
    description:
      "A glacial lake at 5,029m famous for its human skeletal remains visible through the ice. The surrounding ring of Trishul and Nanda Ghunti peaks creates a dramatic circular horizon.",
    region: "Uttarakhand",
    state: "Uttarakhand",
    lat: 30.2432, lng: 79.7207,
    shotTypes: ["landscape", "astro"],
    bestMonths: [5, 6, 9, 10],
    bestTimeOfDay: ["sunrise", "night"],
    crowdLevel: "low",
    accessibility: "difficult",
    monsoonAccessible: false,
    tips: "8-day trek. Essential gear: crampons and ice axe. Milky Way shoots at 5000m are extraordinary.",
    coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    tags: ["glacier", "lake", "trekking", "astro", "altitude"],
    elevation: 5029,
    featured: false,
  },
  {
    id: "har-ki-dun-valley",
    name: "Har Ki Dun Valley – Cradle of the World",
    description:
      "A glacial valley shaped like a cradle, ringed by Swargarohini peaks. The ancient Osla village in the foreground and waterfalls give you layers to work with throughout the day.",
    region: "Uttarakhand",
    state: "Uttarakhand",
    lat: 31.1275, lng: 78.4131,
    shotTypes: ["landscape", "portrait"],
    bestMonths: [4, 5, 6, 9, 10, 11],
    bestTimeOfDay: ["sunrise", "golden_hour_am", "golden_hour_pm"],
    crowdLevel: "low",
    accessibility: "difficult",
    monsoonAccessible: false,
    tips: "Stay at the Forest Rest House for pre-dawn position. 22km trek from Sankri.",
    coverImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    tags: ["valley", "village", "snow-peaks", "trekking"],
    elevation: 3566,
    featured: false,
  },

  // ── KERALA ────────────────────────────────────────────────────────────────
  {
    id: "alleppey-backwaters-sunrise",
    name: "Alleppey Backwaters – Dawn Houseboat",
    description:
      "The network of canals and coconut-fringed lakes turns golden at dawn. A houseboat on the Vembanad Lake gives you a mobile camera platform—perfect for fishermen silhouettes and mist layers.",
    region: "Kerala",
    state: "Kerala",
    lat: 9.4981, lng: 76.3388,
    shotTypes: ["landscape", "street", "waterscape"],
    bestMonths: [11, 12, 1, 2, 3],
    bestTimeOfDay: ["sunrise", "golden_hour_am", "sunset"],
    crowdLevel: "medium",
    accessibility: "easy",
    monsoonAccessible: false,
    festivalNearby: ["Nehru Trophy Boat Race (Aug)"],
    tips: "Book a houseboat with a sunrise cruise package. The Chinese fishing nets at Kochi are 2h away for a bonus shoot.",
    coverImage: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
    tags: ["backwaters", "houseboat", "mist", "fishermen"],
    featured: true,
  },
  {
    id: "munnar-tea-estates",
    name: "Munnar Tea Estates – Eravikulam Plateau",
    description:
      "Undulating hills carpeted in vivid green tea bushes with mist rolling through at dawn. The Eravikulam National Park adds the endangered Nilgiri Tahr as a wildlife subject.",
    region: "Kerala",
    state: "Kerala",
    lat: 10.0889, lng: 77.0595,
    shotTypes: ["landscape", "wildlife"],
    bestMonths: [10, 11, 12, 1, 2],
    bestTimeOfDay: ["sunrise", "golden_hour_am"],
    crowdLevel: "medium",
    accessibility: "easy",
    monsoonAccessible: false,
    tips: "Best after the monsoon clears in October—the green is electric. Drone regulations apply.",
    coverImage: "https://images.unsplash.com/photo-1545126618-7e9f8d0f2c4e?w=800&q=80",
    tags: ["tea", "mist", "green hills", "Nilgiri Tahr"],
    elevation: 1600,
    featured: true,
  },
  {
    id: "kovalam-lighthouse-beach",
    name: "Kovalam Lighthouse Beach – Sunset Rocks",
    description:
      "The red-and-white striped lighthouse on the headland makes a perfect lead-in element for sunset shots. Long exposures on the rocks below give silky water effects.",
    region: "Kerala",
    state: "Kerala",
    lat: 8.3988, lng: 76.9786,
    shotTypes: ["landscape", "waterscape"],
    bestMonths: [10, 11, 12, 1, 2, 3],
    bestTimeOfDay: ["sunset", "golden_hour_pm", "blue_hour"],
    crowdLevel: "medium",
    accessibility: "easy",
    monsoonAccessible: false,
    tips: "Use ND filters for long exposures on the wave-washed rocks. Check tide tables.",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    tags: ["lighthouse", "rocks", "long-exposure", "beach"],
    featured: false,
  },

  // ── GOA ───────────────────────────────────────────────────────────────────
  {
    id: "chapora-fort-goa",
    name: "Chapora Fort – Vagator Bay Overview",
    description:
      "The ruined laterite fort overlooks the crescent of Vagator Beach and the Arabian Sea. Sunrise from the north bastion gives dramatic sidelight on the red cliffs.",
    region: "Goa",
    state: "Goa",
    lat: 15.6008, lng: 73.7396,
    shotTypes: ["landscape", "architecture"],
    bestMonths: [10, 11, 12, 1, 2],
    bestTimeOfDay: ["sunrise", "golden_hour_am", "sunset"],
    crowdLevel: "medium",
    accessibility: "moderate",
    monsoonAccessible: false,
    tips: "Walk the fort walls carefully—some sections are crumbling. Best in the dry season (Oct–Feb).",
    coverImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80",
    tags: ["fort", "beach", "cliffs", "Vagator"],
    featured: false,
  },

  // ── TAMIL NADU ────────────────────────────────────────────────────────────
  {
    id: "brihadeeswarar-temple-thanjavur",
    name: "Brihadeeswarar Temple – Thanjavur",
    description:
      "A UNESCO Chola masterpiece—the 66m vimana (tower) casts no shadow at noon on certain days. The north-facing tank gives perfect reflections at golden hour.",
    region: "Tamil Nadu",
    state: "Tamil Nadu",
    lat: 10.7825, lng: 79.1318,
    shotTypes: ["architecture", "landscape"],
    bestMonths: [11, 12, 1, 2, 3],
    bestTimeOfDay: ["golden_hour_am", "sunset", "blue_hour"],
    crowdLevel: "medium",
    accessibility: "easy",
    festivalNearby: ["Thaipoosam (Jan/Feb)"],
    tips: "The shadow-less noon phenomenon occurs around May 26 and July 17. Temple tank reflections at dusk are spectacular.",
    coverImage: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80",
    tags: ["UNESCO", "Chola", "temple", "reflection"],
    featured: true,
  },
  {
    id: "pamban-bridge-rameswaram",
    name: "Pamban Bridge – Railway over the Sea",
    description:
      "India's first sea bridge, connecting the mainland to Rameswaram island. The low-angle shot from a boat at sunrise shows the train running across turquoise water.",
    region: "Tamil Nadu",
    state: "Tamil Nadu",
    lat: 9.2764, lng: 79.2101,
    shotTypes: ["architecture", "landscape", "waterscape"],
    bestMonths: [10, 11, 12, 1, 2, 3],
    bestTimeOfDay: ["sunrise", "golden_hour_am"],
    crowdLevel: "low",
    accessibility: "moderate",
    monsoonAccessible: false,
    tips: "Hire a fishing boat for the water-level perspective. Train timings: check Indian Railways app the day before.",
    coverImage: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
    tags: ["bridge", "train", "sea", "engineering"],
    featured: true,
  },

  // ── KARNATAKA ─────────────────────────────────────────────────────────────
  {
    id: "hampi-virupaksha-sunrise",
    name: "Hampi – Hemakuta Hill Sunrise",
    description:
      "The UNESCO boulder landscape of Hampi is like no other on earth. From Hemakuta Hill, watch the sun rise over the Virupaksha Temple spire with the Tungabhadra river glinting below.",
    region: "Karnataka",
    state: "Karnataka",
    lat: 15.3350, lng: 76.4600,
    cameraLat: 15.3365, cameraLng: 76.4582,
    shotTypes: ["architecture", "landscape"],
    bestMonths: [10, 11, 12, 1, 2, 3],
    bestTimeOfDay: ["sunrise", "golden_hour_am", "blue_hour"],
    crowdLevel: "medium",
    accessibility: "moderate",
    monsoonAccessible: false,
    festivalNearby: ["Vijayadasami (Oct)"],
    tips: "Climb Matanga Hill for the 360° panorama of the entire boulder landscape. 45-min scramble.",
    coverImage: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&q=80",
    tags: ["UNESCO", "boulders", "ruins", "river"],
    featured: true,
  },
  {
    id: "coorg-abbey-falls",
    name: "Coorg – Abbey Falls Mist",
    description:
      "A 70ft waterfall framed by overhanging coffee and spice plantations. The finest light is just after the monsoon when flow is maximum and morning mist still lingers.",
    region: "Karnataka",
    state: "Karnataka",
    lat: 12.3910, lng: 75.7307,
    shotTypes: ["waterscape", "landscape"],
    bestMonths: [9, 10, 11],
    bestTimeOfDay: ["golden_hour_am", "midday"],
    crowdLevel: "medium",
    accessibility: "easy",
    monsoonAccessible: true,
    tips: "Use a polariser to cut glare off the water and reveal detail. ND filter for silky water at 1/4s.",
    coverImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80",
    tags: ["waterfall", "coffee", "mist", "greenery"],
    featured: false,
  },

  // ── MAHARASHTRA ───────────────────────────────────────────────────────────
  {
    id: "ajanta-caves-sunrise",
    name: "Ajanta Caves – Gorge Viewpoint",
    description:
      "The horseshoe gorge of the Waghora River cuts below the cave-studded cliff. Sunrise from the viewpoint at the far end gives raking light on all 30 cave facades simultaneously.",
    region: "Maharashtra",
    state: "Maharashtra",
    lat: 20.5519, lng: 75.7033,
    shotTypes: ["architecture", "landscape"],
    bestMonths: [10, 11, 12, 1, 2, 3],
    bestTimeOfDay: ["sunrise", "golden_hour_am"],
    crowdLevel: "medium",
    accessibility: "easy",
    monsoonAccessible: false,
    festivalNearby: ["Ellora Ajanta Festival (Mar)"],
    tips: "Get the shared jeep from the main gate to the viewpoint—steep road. Tripods allowed outside caves only.",
    coverImage: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&q=80",
    tags: ["UNESCO", "caves", "Buddhist", "gorge"],
    featured: false,
  },
  {
    id: "lonavala-tiger-point",
    name: "Lonavala – Tiger's Leap / Duke's Nose",
    description:
      "During monsoon, the Sahyadri escarpment is draped in waterfalls and clouds boil up from the valleys below. Duke's Nose ridge gives a dramatic nose-dive view into the Bor Ghat.",
    region: "Maharashtra",
    state: "Maharashtra",
    lat: 18.7409, lng: 73.4054,
    shotTypes: ["landscape", "aerial"],
    bestMonths: [7, 8, 9],
    bestTimeOfDay: ["midday", "golden_hour_pm"],
    crowdLevel: "high",
    accessibility: "easy",
    monsoonAccessible: true,
    tips: "Go on weekdays to avoid crowds. Cloudy days are better than sunny ones here—the drama is in the clouds.",
    coverImage: "https://images.unsplash.com/photo-1536514498073-50e69d39c6cf?w=800&q=80",
    tags: ["monsoon", "escarpment", "waterfalls", "clouds"],
    elevation: 650,
    featured: false,
  },

  // ── WEST BENGAL ───────────────────────────────────────────────────────────
  {
    id: "tiger-hill-darjeeling",
    name: "Tiger Hill – Kangchenjunga Sunrise",
    description:
      "On clear mornings, five of the world's highest peaks line the horizon. Kangchenjunga turns rose-gold as the sun rises behind you. The tea garden foreground adds depth.",
    region: "West Bengal",
    state: "West Bengal",
    lat: 27.0436, lng: 88.2642,
    shotTypes: ["landscape"],
    bestMonths: [10, 11, 3, 4],
    bestTimeOfDay: ["sunrise"],
    crowdLevel: "high",
    accessibility: "easy",
    monsoonAccessible: false,
    tips: "October–November post-monsoon has best clarity. Book a jeep at 3:30 AM from Darjeeling town.",
    coverImage: "https://images.unsplash.com/photo-1571122168489-a86bf012a2ca?w=800&q=80",
    tags: ["Kangchenjunga", "Himalayas", "sunrise", "tea-garden"],
    elevation: 2590,
    featured: true,
  },
  {
    id: "sundarbans-mangrove",
    name: "Sundarbans – Sajnekhali Mangrove Delta",
    description:
      "The world's largest mangrove delta photographed from a boat. Royal Bengal tigers, saltwater crocodiles, and spotted deer are the wildlife subjects. Misty sunrise over the tidal creeks is ethereal.",
    region: "West Bengal",
    state: "West Bengal",
    lat: 21.9330, lng: 88.8830,
    shotTypes: ["wildlife", "landscape", "waterscape"],
    bestMonths: [11, 12, 1, 2, 3],
    bestTimeOfDay: ["sunrise", "golden_hour_am"],
    crowdLevel: "low",
    accessibility: "difficult",
    monsoonAccessible: false,
    tips: "All photography done from a government boat. 400–600mm lens essential for tiger sightings.",
    coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    tags: ["mangrove", "tiger", "delta", "UNESCO"],
    featured: false,
  },

  // ── MEGHALAYA ─────────────────────────────────────────────────────────────
  {
    id: "dawki-river-meghalaya",
    name: "Dawki River – Crystal Transparent Boats",
    description:
      "The Umngot River is so clear that boats appear to float in mid-air. The best shots are from the bridge at Dawki or from a rented rowboat looking up at the Jaintia hills.",
    region: "Meghalaya",
    state: "Meghalaya",
    lat: 25.2041, lng: 92.0262,
    shotTypes: ["landscape", "waterscape"],
    bestMonths: [10, 11, 12, 1, 2, 3],
    bestTimeOfDay: ["midday", "golden_hour_pm"],
    crowdLevel: "medium",
    accessibility: "easy",
    monsoonAccessible: false,
    tips: "Best clarity in winter—monsoon muddies the water completely. Aerial/drone gives the floating-boat illusion best.",
    coverImage: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&q=80",
    tags: ["transparent water", "boats", "river", "crystal"],
    featured: true,
  },
  {
    id: "living-root-bridges-meghalaya",
    name: "Living Root Bridges – Nongriat Village",
    description:
      "Khasi tribal bridges grown from Indian rubber-tree roots over 15–500 years. The double-decker bridge at Nongriat is the holy grail—best shot in the morning before haze builds.",
    region: "Meghalaya",
    state: "Meghalaya",
    lat: 25.3218, lng: 91.6988,
    shotTypes: ["architecture", "landscape"],
    bestMonths: [10, 11, 12, 1, 2, 3],
    bestTimeOfDay: ["golden_hour_am", "midday"],
    crowdLevel: "medium",
    accessibility: "difficult",
    monsoonAccessible: false,
    tips: "3500-step descent from Tyrna village. Go early—crowds arrive by 9am. CPL filter reduces leaf glare.",
    coverImage: "https://images.unsplash.com/photo-1601647013450-f1e4b9e3e1c7?w=800&q=80",
    tags: ["root bridge", "living", "jungle", "Khasi"],
    featured: true,
  },

  // ── GUJARAT ───────────────────────────────────────────────────────────────
  {
    id: "rann-of-kutch",
    name: "Rann of Kutch – Full Moon White Desert",
    description:
      "The world's largest salt flat turns blinding white under a full moon. The Rann Utsav festival lights up the kutch and traditional performers in colourful dress against the white desert are iconic.",
    region: "Gujarat",
    state: "Gujarat",
    lat: 23.7333, lng: 69.9667,
    shotTypes: ["landscape", "portrait", "astro"],
    bestMonths: [11, 12, 1, 2],
    bestTimeOfDay: ["sunset", "night", "blue_hour"],
    crowdLevel: "high",
    accessibility: "easy",
    monsoonAccessible: false,
    festivalNearby: ["Rann Utsav (Nov–Feb)"],
    tips: "Full moon nights are extraordinary—book accommodation at the Rann Utsav village. Bring a wide-angle for the horizon.",
    coverImage: "https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=800&q=80",
    tags: ["salt flat", "white desert", "full moon", "festival"],
    featured: true,
  },

  // ── SIKKIM ────────────────────────────────────────────────────────────────
  {
    id: "gurudongmar-lake-sikkim",
    name: "Gurudongmar Lake – Sacred High-altitude Lake",
    description:
      "One of the highest lakes in the world at 5,430m. The deep blue water ringed by barren peaks creates a hypnotic landscape. Sunrise here is among the most dramatic in India.",
    region: "Sikkim",
    state: "Sikkim",
    lat: 28.0268, lng: 88.7046,
    shotTypes: ["landscape", "astro"],
    bestMonths: [5, 6, 9, 10],
    bestTimeOfDay: ["sunrise", "golden_hour_am"],
    crowdLevel: "low",
    accessibility: "difficult",
    monsoonAccessible: false,
    tips: "Restricted area permit required. Road opens May–June only. Altitude sickness is real—acclimatise.",
    coverImage: "https://images.unsplash.com/photo-1606298855672-3efb63017be8?w=800&q=80",
    tags: ["altitude", "sacred lake", "Sikkim", "barren"],
    elevation: 5430,
    featured: false,
  },

  // ── ANDHRA PRADESH ────────────────────────────────────────────────────────
  {
    id: "araku-valley-sunrise",
    name: "Araku Valley – Coffee Plantation Sunrise",
    description:
      "A high-altitude valley in the Eastern Ghats with terraced coffee and pepper plantations. Morning fog fills the valley floor while the tribal Kondh villages provide human interest.",
    region: "Andhra Pradesh",
    state: "Andhra Pradesh",
    lat: 18.3296, lng: 82.8757,
    shotTypes: ["landscape", "portrait"],
    bestMonths: [10, 11, 12, 1, 2],
    bestTimeOfDay: ["sunrise", "golden_hour_am"],
    crowdLevel: "low",
    accessibility: "easy",
    monsoonAccessible: false,
    tips: "The Kirandul Express train through the Eastern Ghats is a bonus — 58 tunnels and extraordinary viaducts.",
    coverImage: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800&q=80",
    tags: ["coffee", "valley", "tribal", "Eastern Ghats"],
    elevation: 900,
    featured: false,
  },

  // ── VARANASI ─────────────────────────────────────────────────────────────
  {
    id: "varanasi-ghats-dawn",
    name: "Varanasi Ghats – Dawn Boat Ride",
    description:
      "The most photographed ghats in India. A boat on the Ganges at dawn gives you the full panorama of 88 ghats with priests performing Aarti, smoke from the Manikarnika cremation ghat, and pilgrims bathing.",
    region: "Uttar Pradesh",
    state: "Uttar Pradesh",
    lat: 25.3176, lng: 83.0062,
    cameraLat: 25.3100, cameraLng: 83.0100,
    shotTypes: ["street", "portrait", "landscape"],
    bestMonths: [10, 11, 12, 1, 2, 3],
    bestTimeOfDay: ["sunrise", "golden_hour_am", "blue_hour"],
    crowdLevel: "high",
    accessibility: "easy",
    monsoonAccessible: false,
    festivalNearby: ["Dev Deepawali (Nov)", "Ganga Aarti (daily)"],
    tips: "Hire a boat for 90min at dawn—negotiate price the night before. 85mm is ideal for priests at Aarti ceremony.",
    coverImage: "https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=800&q=80",
    tags: ["ghats", "Ganges", "ritual", "sunrise", "Aarti"],
    featured: true,
  },
];

export const MONTH_NAMES = [
  "", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

export const ALL_REGIONS = [...new Set(spots.map((s) => s.region))].sort();

export const ALL_SHOT_TYPES = [
  "landscape", "architecture", "wildlife", "street",
  "astro", "portrait", "aerial", "waterscape",
] as const;

export function getSpotById(id: string): PhotoSpot | undefined {
  return spots.find((s) => s.id === id);
}

export function filterSpots(opts: {
  region?: string;
  shotType?: string;
  month?: number;
  search?: string;
}): PhotoSpot[] {
  return spots.filter((s) => {
    if (opts.region && s.region !== opts.region) return false;
    if (opts.shotType && !s.shotTypes.includes(opts.shotType as never)) return false;
    if (opts.month && !s.bestMonths.includes(opts.month)) return false;
    if (opts.search) {
      const q = opts.search.toLowerCase();
      if (
        !s.name.toLowerCase().includes(q) &&
        !s.region.toLowerCase().includes(q) &&
        !s.tags.join(" ").toLowerCase().includes(q)
      )
        return false;
    }
    return true;
  });
}
